replicaCount: 1
image:
  repository: dimozone/fleet-tenancy-api
  pullPolicy: IfNotPresent
  tag: a466569
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
env:
  ENVIRONMENT: dev
  LOG_LEVEL: info
  SERVICE_NAME: fleet-tenancy-api
  API_PORT: '8084'
  MONITORING_PORT: '8085'
  DB_PORT: '5432'
  DB_NAME: fleet_tenancy_api
  DB_MAX_OPEN_CONNECTIONS: '10'
  DB_MAX_IDLE_CONNECTIONS: '3'
  DB_SSL_MODE: require
  JWT_KEY_SET_URL: https://auth.dimo.zone/keys
service:
  type: ClusterIP
  ports:
    http:
      port: 8084
      targetPort: http
      protocol: TCP
ports:
  - name: http
    containerPort: 8084
    protocol: TCP
resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
autoscaling:
  enabled: false
nodeSelector: {}
tolerations: []
affinity: {}
podDisruptionBudget:
  minAvailable: 0
